sudo: false
language: node_js
cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '4'
  - '6'
  - '8'
  - 'node'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune

script:
  - npm run pre-release

after_success:
  - npm run upload-coverage
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
